openapi: 3.1.0
info:
  title: Hello World
  summary: Hatch demo for Python Rennes Meetup 04-2024.
  version: 0.4.0
  license:
    name: MIT
    identifier: MIT
  contact:
    name: "Fr\xE9d\xE9ric Collonval"
    email: frederic.collonval@webscit.com
servers:
- url: /openapi
paths:
  /greeting/{name}:
    post:
      description: Generates a greeting message.
      operationId: hatch_demo.hello.post_greeting
      parameters:
      - description: Name of the person to greet.
        in: path
        name: name
        required: true
        schema:
          example: dave
          type: string
      responses:
        '200':
          content:
            text/plain:
              schema:
                example: hello dave!
                type: string
          description: greeting response
      summary: Generate greeting
components:
  schemas:
    user:
      type: object
      properties:
        name:
          type: string
      required:
      - name
