[build-system]
requires = ["hatchling", "hatch-openapi-version @ file://./hatch-openapi-version"]
build-backend = "hatchling.build"

[project]
name = "hatch-demo"
dynamic = ["version", "authors", "description", "license"]
readme = "README.md"
requires-python = ">=3.8"
keywords = []
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
  "connexion~=3.0",
  "pydantic~=2.0",
  "uvicorn"
]

[project.optional-dependencies]
dev = [
  "pyyaml~=6.0",
  "hatchling>=0.21.0",
  "ruff",
]

[project.urls]
Documentation = "https://github.com/fcollonval/hatch-demo#readme"
Issues = "https://github.com/fcollonval/hatch-demo/issues"
Source = "https://github.com/fcollonval/hatch-demo"

[tool.hatch.version]
# First installation in dev mode cannot use itself - fallback to default
# path = "src/hatch_demo/_version.py"
# Except the first installation - this should work
source = "openapi"
path = "src/hatch_demo/spec/openapi.yaml"

[tool.hatch.metadata.hooks.custom]

[tool.hatch.build.hooks.custom]

[tool.hatch.build.hooks.version]
path = "src/hatch_demo/_version.py"
template = """
# This file is auto-generated by Hatchling. As such, do not:
#   - modify
#   - track in version control e.g. be sure to add to .gitignore
__version__ = '{version}'"""
